dist: bionic
env:
  global:
    - TZ=America/Los_Angeles
language: python
python:
  - '3.9'
services:
  - postgresql
sudo: required
install:
  - python --version
  - rvm install 2.7.1
  - pip install 'urllib3[secure]'
  - pip install -r requirements.txt
  - bundle install
  - pip show csvkit
cache:
  - bundler
  - pip
addons:
  postgresql: '9.6'
notifications:
  email:
    - mike.ubell@gmail.com
script:
  - make clean && make download -j2 && make import -j2 && make process && ./bin/travis-deploy && ./bin/travis-reindex
