dist: bionic
env:
  global:
    - TZ=America/Los_Angeles
    - PGPORT=5433
language: python
python:
  - '3.9'
services:
  - postgresql
sudo: required
install:
  - python --version
  - rvm install 3.3.4
  - pip install 'urllib3[secure]'
  - pip install -r requirements.txt
  - bundle install
  - pip show csvkit
cache:
  - bundler
  - pip
addons:
  postgresql: "16"
  apt:
    packages:
    - postgresql-16
    - postgresql-client-16
notifications:
  email:
    - mike.ubell@gmail.com
script:
  - make clean && make download -j2 && make import -j2 && make process && ./bin/travis-deploy && ./bin/travis-reindex
