version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.9
        USER_UID: 1000
        USER_GID: 1000

    environment:
      PGHOST: localhost
      PGDATABASE: disclosure-backend
      PGUSER: app_user
      
    volumes:
      - ..:/workspace:cached

    # Overrides default so things don't shut down after the process ends
    command: sleep infinity

    # Runs app on the same network as the database container,
    # allows "forwardPorts" in devcontainer.json function
    network_mode: service:db

  db:
    image: postgres:latest
    # image: postgres:15.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #- ../pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: "disclosure-backend"
      POSTGRES_PASSWORD: app_password

volumes:
  postgres-data:
