CREATE TABLE "496" (
	"Filer_ID" VARCHAR(9) NOT NULL, 
	"Filer_NamL" VARCHAR(183) NOT NULL, 
	"Report_Num" VARCHAR(3) NOT NULL, 
	"Committee_Type" VARCHAR(4), 
	"Rpt_Date" DATE NOT NULL, 
	"From_Date" DATE, 
	"Thru_Date" DATE, 
	"Elect_Date" DATE, 
	"Rec_Type" VARCHAR(4) NOT NULL, 
	"Form_Type" VARCHAR(4) NOT NULL, 
	"Tran_ID" VARCHAR(12) NOT NULL, 
	"Amount" INTEGER NOT NULL, 
	"Exp_Date" DATE NOT NULL, 
	"Date_Thru" VARCHAR(32), 
	"Expn_Dscr" VARCHAR(90), 
	"Memo_Code" VARCHAR(32), 
	"Memo_RefNo" VARCHAR(13), 
	"Bal_Name" VARCHAR(171), 
	"Bal_Num" VARCHAR(4), 
	"Bal_Juris" VARCHAR(31), 
	"Sup_Opp_Cd" VARCHAR(1) NOT NULL, 
	"Cand_NamL" VARCHAR(32), 
	"Cand_NamF" VARCHAR(32), 
	"Cand_NamT" VARCHAR(32), 
	"Cand_NamS" VARCHAR(32), 
	"Office_Cd" VARCHAR(4), 
	"Offic_Dscr" VARCHAR(64), 
	"Juris_Cd" VARCHAR(4), 
	"Juris_Dscr" VARCHAR(31), 
	"Dist_No" VARCHAR(4), 
	"Rpt_ID_Num" VARCHAR(15) NOT NULL
);
