CREATE TABLE "497" (
	"Filer_ID" VARCHAR(9), 
	"Filer_NamL" VARCHAR(183) NOT NULL, 
	"Report_Num" VARCHAR(3) NOT NULL, 
	"Committee_Type" VARCHAR(4), 
	"Rpt_Date" DATE NOT NULL, 
	"From_Date" DATE, 
	"Thru_Date" DATE, 
	"Elect_Date" DATE, 
	"Rec_Type" VARCHAR(4) NOT NULL, 
	"Form_Type" VARCHAR(6) NOT NULL, 
	"Tran_ID" VARCHAR(12) NOT NULL, 
	"Entity_Cd" VARCHAR(3) NOT NULL, 
	"Enty_NamL" VARCHAR(169) NOT NULL, 
	"Enty_NamF" VARCHAR(41), 
	"Enty_NamT" VARCHAR(4), 
	"Enty_NamS" VARCHAR(4), 
	"Enty_Adr1" VARCHAR(32), 
	"Enty_Adr2" VARCHAR(32), 
	"Enty_City" VARCHAR(17), 
	"Enty_ST" VARCHAR(4), 
	"Enty_Zip4" VARCHAR(10), 
	"Ctrib_Emp" VARCHAR(50), 
	"Ctrib_Occ" VARCHAR(37), 
	"Ctrib_Self" VARCHAR(32), 
	"Elec_Date" DATE, 
	"Ctrib_Date" DATE NOT NULL, 
	"Date_Thru" VARCHAR(32), 
	"Amount" FLOAT NOT NULL, 
	"Cmte_ID" VARCHAR(9), 
	"Cand_NamL" VARCHAR(172), 
	"Cand_NamF" VARCHAR(15), 
	"Cand_NamT" VARCHAR(32), 
	"Cand_NamS" VARCHAR(32), 
	"Office_Cd" VARCHAR(4), 
	"Offic_Dscr" VARCHAR(40), 
	"Juris_Cd" VARCHAR(4), 
	"Juris_Dscr" VARCHAR(38), 
	"Dist_No" VARCHAR(4), 
	"Off_S_H_Cd" VARCHAR(4), 
	"Bal_Name" VARCHAR(188), 
	"Bal_Num" VARCHAR(4), 
	"Bal_Juris" VARCHAR(31), 
	"Memo_Code" VARCHAR(32), 
	"Memo_RefNo" VARCHAR(13), 
	"Rpt_ID_Num" VARCHAR(14) NOT NULL
);
