CREATE TABLE "B1-Loans" (
	"Filer_ID" VARCHAR(7) NOT NULL, 
	"Filer_NamL" VARCHAR(183) NOT NULL, 
	"Report_Num" VARCHAR(3) NOT NULL, 
	"Committee_Type" VARCHAR(3) NOT NULL, 
	"Rpt_Date" DATE NOT NULL, 
	"From_Date" DATE NOT NULL, 
	"Thru_Date" DATE NOT NULL, 
	"Elect_Date" DATE, 
	"tblCover_Office_Cd" VARCHAR(32), 
	"tblCover_Offic_Dscr" VARCHAR(32), 
	"Rec_Type" VARCHAR(4) NOT NULL, 
	"Form_Type" VARCHAR(2) NOT NULL, 
	"Tran_ID" VARCHAR(12) NOT NULL, 
	"Entity_Cd" VARCHAR(3) NOT NULL, 
	"Lndr_NamL" VARCHAR(48) NOT NULL, 
	"Lndr_NamF" VARCHAR(14), 
	"Lndr_NamT" VARCHAR(4), 
	"Lndr_NamS" VARCHAR(4), 
	"Loan_Adr1" VARCHAR(32), 
	"Loan_Adr2" VARCHAR(32), 
	"Loan_City" VARCHAR(13), 
	"Loan_ST" VARCHAR(4), 
	"Loan_Zip4" VARCHAR(10), 
	"Loan_Date1" DATE NOT NULL, 
	"Loan_Date2" DATE, 
	"Loan_Amt1" FLOAT NOT NULL, 
	"Loan_Amt2" FLOAT NOT NULL, 
	"Loan_Amt3" FLOAT NOT NULL, 
	"Loan_Amt4" FLOAT NOT NULL, 
	"Loan_Rate" VARCHAR(5), 
	"Loan_EMP" VARCHAR(64), 
	"Loan_OCC" VARCHAR(43), 
	"Loan_Self" BOOLEAN NOT NULL, 
	"Cmte_ID" INTEGER, 
	"Tres_NamL" VARCHAR(32), 
	"Tres_NamF" VARCHAR(32), 
	"Tres_NamT" VARCHAR(32), 
	"Tres_NamS" VARCHAR(32), 
	"Tres_Adr1" VARCHAR(32), 
	"Tres_Adr2" VARCHAR(32), 
	"Tres_City" VARCHAR(32), 
	"Tres_ST" VARCHAR(32), 
	"Tres_ZIP4" VARCHAR(32), 
	"B2Lender_Name-Inter_name" VARCHAR(32), 
	"Intr_NamF" VARCHAR(32), 
	"Intr_NamT" VARCHAR(32), 
	"Intr_NamS" VARCHAR(32), 
	"Intr_Adr1" VARCHAR(32), 
	"Intr_Adr2" VARCHAR(32), 
	"Intr_City" VARCHAR(32), 
	"Intr_ST" VARCHAR(32), 
	"Intr_ZIP4" VARCHAR(32), 
	"Memo_Code" VARCHAR(6), 
	"Memo_RefNo" VARCHAR(32), 
	"BakRef_TID" VARCHAR(32), 
	"XRef_SchNm" VARCHAR(32), 
	"XRef_Match" VARCHAR(32), 
	"Loan_Amt5" FLOAT NOT NULL, 
	"Loan_Amt6" FLOAT NOT NULL, 
	"Loan_Amt7" FLOAT NOT NULL, 
	"Loan_Amt8" FLOAT NOT NULL
);
