CREATE TABLE candidates (
	election_name VARCHAR(18) NOT NULL, 
	"Candidate" VARCHAR(31) NOT NULL, 
	"FPPC" INTEGER, 
	"Committee_Name" VARCHAR(78), 
	"Aliases" VARCHAR(30), 
	"Office" VARCHAR(31) NOT NULL, 
	"Incumbent" BOOLEAN, 
	"Accepted_expenditure_ceiling" BOOLEAN, 
	"Public_Funding_Received" VARCHAR(10), 
	"Contact_Email" VARCHAR(36), 
	"Website" VARCHAR(68), 
	"Twitter" VARCHAR(17), 
	"Facebook" VARCHAR(91), 
	"Instagram" VARCHAR(91), 
	"Party_Affiliation" VARCHAR(11), 
	"Occupation" VARCHAR(78), 
	"Bio" VARCHAR(1295), 
	"Photo" VARCHAR(85), 
	"VotersEdge" VARCHAR(148), 
	"Start_Date" DATE, 
	"End_Date" DATE, 
	"Internal_Notes" VARCHAR(267), 
	data_warning VARCHAR(232), 
	is_winner BOOLEAN, 
	ballot_status VARCHAR(13), 
	map_app VARCHAR(127), 
	has_pending BOOLEAN
);
