CREATE TABLE candidates (
	election_name VARCHAR(18) NOT NULL, 
	"Candidate" VARCHAR(31) NOT NULL, 
	"FPPC" VARCHAR(16), 
	"Committee_Name" VARCHAR(78), 
	"Aliases" VARCHAR(64), 
	"Office" VARCHAR(64) NOT NULL, 
	"Incumbent" BOOLEAN, 
	"Accepted_expenditure_ceiling" BOOLEAN, 
	"Public_Funding_Received" VARCHAR(10), 
	"Contact_Email" VARCHAR(128), 
	"Website" VARCHAR(128), 
	"Twitter" VARCHAR(128), 
	"Facebook" VARCHAR(128), 
	"Instagram" VARCHAR(128), 
	"Party_Affiliation" VARCHAR(64), 
	"Occupation" VARCHAR(128), 
	"Bio" VARCHAR(1295), 
	"Photo" VARCHAR(128), 
	"VotersEdge" VARCHAR(148), 
	"Start_Date" DATE, 
	"End_Date" DATE, 
	"Internal_Notes" VARCHAR(267), 
	data_warning VARCHAR(232), 
	is_winner BOOLEAN, 
	ballot_status VARCHAR(13), 
	map_app VARCHAR(127), 
	has_pending BOOLEAN
);
