CREATE TABLE "F-Expenses" (
	"Filer_ID" VARCHAR(7) NOT NULL, 
	"Filer_NamL" VARCHAR(183) NOT NULL, 
	"Report_Num" VARCHAR(3) NOT NULL, 
	"Committee_Type" VARCHAR(3) NOT NULL, 
	"Rpt_Date" DATE NOT NULL, 
	"From_Date" DATE NOT NULL, 
	"Thru_Date" DATE NOT NULL, 
	"Elect_Date" DATE, 
	"tblCover_Office_Cd" VARCHAR(32), 
	"tblCover_Offic_Dscr" VARCHAR(32), 
	"Rec_Type" VARCHAR(4) NOT NULL, 
	"Form_Type" BOOLEAN NOT NULL, 
	"Tran_ID" VARCHAR(16) NOT NULL, 
	"Entity_Cd" VARCHAR(3) NOT NULL, 
	"Payee_NamL" VARCHAR(128) NOT NULL, 
	"Payee_NamF" VARCHAR(32), 
	"Payee_NamT" VARCHAR(32), 
	"Payee_NamS" VARCHAR(32), 
	"Payee_Adr1" VARCHAR(32), 
	"Payee_Adr2" VARCHAR(32), 
	"Payee_City" VARCHAR(32) NOT NULL, 
	"Payee_State" VARCHAR(2) NOT NULL, 
	"Payee_Zip4" VARCHAR(10) NOT NULL, 
	"Beg_Bal" FLOAT NOT NULL, 
	"Amt_Incur" FLOAT NOT NULL, 
	"Amt_Paid" FLOAT NOT NULL, 
	"End_Bal" FLOAT NOT NULL, 
	"Expn_Code" VARCHAR(4), 
	"Expn_Dscr" VARCHAR(134), 
	"Cmte_ID" VARCHAR(7), 
	"Tres_NamL" VARCHAR(32), 
	"Tres_NamF" VARCHAR(32), 
	"Tres_NamT" VARCHAR(32), 
	"Tres_NamS" VARCHAR(32), 
	"Tres_Adr1" VARCHAR(32), 
	"Tres_Adr2" VARCHAR(32), 
	"Tres_City" VARCHAR(32), 
	"Tres_ST" VARCHAR(32), 
	"Tres_ZIP4" VARCHAR(32), 
	"Memo_Code" VARCHAR(32), 
	"Memo_RefNo" VARCHAR(16), 
	"BakRef_TID" VARCHAR(32), 
	"XRef_SchNm" VARCHAR(32), 
	"XRef_Match" VARCHAR(4)
);
