CREATE TABLE "F461P5-Expenditure" (
	"Filer_ID" VARCHAR(9), 
	"Filer_NamL" VARCHAR(183) NOT NULL, 
	"Report_Num" VARCHAR(3) NOT NULL, 
	"Committee_Type" VARCHAR(3) NOT NULL, 
	"Rpt_Date" DATE NOT NULL, 
	"From_Date" DATE NOT NULL, 
	"Thru_Date" DATE NOT NULL, 
	"Elect_Date" DATE, 
	"tblCover_Office_Cd" VARCHAR(32), 
	"tblCover_Offic_Dscr" VARCHAR(32), 
	"Rec_Type" VARCHAR(4) NOT NULL, 
	"Form_Type" VARCHAR(6) NOT NULL, 
	"Tran_ID" VARCHAR(12) NOT NULL, 
	"Entity_Cd" VARCHAR(4), 
	"Payee_NamL" VARCHAR(144) NOT NULL, 
	"Payee_NamF" VARCHAR(20), 
	"Payee_NamT" VARCHAR(32), 
	"Payee_NamS" VARCHAR(32), 
	"Payee_Adr1" VARCHAR(32), 
	"Payee_Adr2" VARCHAR(32), 
	"Payee_City" VARCHAR(14) NOT NULL, 
	"Payee_State" VARCHAR(4), 
	"Payee_Zip4" VARCHAR(10), 
	"Expn_Date" DATE NOT NULL, 
	"Amount" FLOAT NOT NULL, 
	"Cum_YTD" FLOAT NOT NULL, 
	"Expn_ChkNo" VARCHAR(10), 
	"Expn_Code" VARCHAR(3) NOT NULL, 
	"Expn_Dscr" VARCHAR(81), 
	"Agent_NamL" VARCHAR(32), 
	"Agent_NamF" VARCHAR(32), 
	"Agent_NamT" VARCHAR(32), 
	"Agent_NamS" VARCHAR(32), 
	"Cmte_ID" VARCHAR(7), 
	"Tres_NamL" VARCHAR(5), 
	"Tres_NamF" VARCHAR(5), 
	"Tres_NamT" VARCHAR(32), 
	"Tres_NamS" VARCHAR(32), 
	"Tres_Adr1" VARCHAR(32), 
	"Tres_Adr2" VARCHAR(32), 
	"Tres_City" VARCHAR(7), 
	"Tres_ST" VARCHAR(4), 
	"Tres_ZIP4" INTEGER, 
	"Cand_NamL" VARCHAR(47), 
	"Cand_NamF" VARCHAR(9), 
	"Cand_NamT" VARCHAR(7), 
	"Cand_NamS" VARCHAR(4), 
	"Office_Cd" VARCHAR(4), 
	"Offic_Dscr" VARCHAR(35), 
	"Juris_Cd" VARCHAR(4), 
	"Juris_Dscr" VARCHAR(31), 
	"Dist_No" VARCHAR(4), 
	"Off_S_H_Cd" VARCHAR(4), 
	"Bal_Name" VARCHAR(138), 
	"Bal_Num" VARCHAR(4), 
	"Bal_Juris" VARCHAR(32), 
	"Sup_Opp_Cd" VARCHAR(4), 
	"Memo_Code" VARCHAR(4), 
	"Memo_RefNo" VARCHAR(11), 
	"BakRef_TID" VARCHAR(12), 
	"G_From_E_F" VARCHAR(32), 
	"XRef_SchNm" VARCHAR(32), 
	"XRef_Match" VARCHAR(32), 
	"EmplBus_CB" VARCHAR(4), 
	"Bus_Name" VARCHAR(28), 
	"Bus_Adr1" VARCHAR(33), 
	"Bus_Adr2" VARCHAR(10), 
	"Bus_City" VARCHAR(13), 
	"Bus_ST" VARCHAR(4), 
	"Bus_ZIP4" INTEGER, 
	"Bus_Inter" VARCHAR(37), 
	"BusAct_CB" VARCHAR(4), 
	"BusActvity" VARCHAR(61), 
	"Assoc_CB" VARCHAR(66), 
	"Assoc_Int" VARCHAR(32), 
	"Other_CB" VARCHAR(32), 
	"Other_Int" VARCHAR(32)
);
