CREATE TABLE "F465P3-Expenditure" (
	"Filer_ID" INTEGER NOT NULL, 
	"Filer_NamL" VARCHAR(183) NOT NULL, 
	"Report_Num" INTEGER NOT NULL, 
	"Committee_Type" VARCHAR(3) NOT NULL, 
	"Rpt_Date" DATE NOT NULL, 
	"From_Date" DATE NOT NULL, 
	"Thru_Date" DATE NOT NULL, 
	"Elect_Date" DATE NOT NULL, 
	"tblCover_Office_Cd" VARCHAR(32), 
	"tblCover_Offic_Dscr" VARCHAR(32), 
	"Rec_Type" VARCHAR(4) NOT NULL, 
	"Form_Type" VARCHAR(6) NOT NULL, 
	"Tran_ID" VARCHAR(10) NOT NULL, 
	"Entity_Cd" VARCHAR(3) NOT NULL, 
	"Payee_NamL" VARCHAR(31) NOT NULL, 
	"Payee_NamF" VARCHAR(4), 
	"Payee_NamT" VARCHAR(32), 
	"Payee_NamS" VARCHAR(32), 
	"Payee_Adr1" VARCHAR(32), 
	"Payee_Adr2" VARCHAR(32), 
	"Payee_City" VARCHAR(13) NOT NULL, 
	"Payee_State" VARCHAR(2) NOT NULL, 
	"Payee_Zip4" INTEGER NOT NULL, 
	"Expn_Date" DATE NOT NULL, 
	"Amount" FLOAT NOT NULL, 
	"Cum_YTD" FLOAT, 
	"Expn_ChkNo" VARCHAR(32), 
	"Expn_Code" VARCHAR(4), 
	"Expn_Dscr" VARCHAR(98) NOT NULL, 
	"Agent_NamL" VARCHAR(28), 
	"Agent_NamF" VARCHAR(32), 
	"Agent_NamT" VARCHAR(32), 
	"Agent_NamS" VARCHAR(32), 
	"Cmte_ID" VARCHAR(32), 
	"Tres_NamL" VARCHAR(32), 
	"Tres_NamF" VARCHAR(32), 
	"Tres_NamT" VARCHAR(32), 
	"Tres_NamS" VARCHAR(32), 
	"Tres_Adr1" VARCHAR(32), 
	"Tres_Adr2" VARCHAR(32), 
	"Tres_City" VARCHAR(32), 
	"Tres_ST" VARCHAR(32), 
	"Tres_ZIP4" VARCHAR(32), 
	"Cand_NamL" VARCHAR(25), 
	"Cand_NamF" VARCHAR(32), 
	"Cand_NamT" VARCHAR(32), 
	"Cand_NamS" VARCHAR(32), 
	"Office_Cd" VARCHAR(4), 
	"Offic_Dscr" VARCHAR(12), 
	"Juris_Cd" VARCHAR(4), 
	"Juris_Dscr" VARCHAR(31), 
	"Dist_No" INTEGER, 
	"Off_S_H_Cd" VARCHAR(32), 
	"Bal_Name" VARCHAR(122), 
	"Bal_Num" VARCHAR(4), 
	"Bal_Juris" VARCHAR(19), 
	"Sup_Opp_Cd" VARCHAR(1) NOT NULL, 
	"Memo_Code" VARCHAR(32), 
	"Memo_RefNo" VARCHAR(4), 
	"BakRef_TID" VARCHAR(32), 
	"G_From_E_F" VARCHAR(32), 
	"XRef_SchNm" VARCHAR(32), 
	"XRef_Match" VARCHAR(32)
);
