CREATE TABLE "F496P3-Contributions" (
	"Filer_ID" VARCHAR(7) NOT NULL, 
	"Filer_NamL" VARCHAR(183) NOT NULL, 
	"Report_Num" VARCHAR(3) NOT NULL, 
	"Committee_Type" VARCHAR(4), 
	"Rpt_Date" DATE NOT NULL, 
	"From_Date" DATE, 
	"Thru_Date" DATE, 
	"Elect_Date" DATE, 
	"tblCover_Office_Cd" VARCHAR(32), 
	"tblCover_Offic_Dscr" VARCHAR(32), 
	"Rec_Type" VARCHAR(4) NOT NULL, 
	"Form_Type" VARCHAR(6) NOT NULL, 
	"Tran_ID" VARCHAR(12) NOT NULL, 
	"Entity_Cd" VARCHAR(3) NOT NULL, 
	"Tran_NamL" VARCHAR(137) NOT NULL, 
	"Tran_NamF" VARCHAR(36), 
	"Tran_NamT" VARCHAR(4), 
	"Tran_NamS" VARCHAR(32), 
	"Tran_Adr1" VARCHAR(32), 
	"Tran_Adr2" VARCHAR(32), 
	"Tran_City" VARCHAR(17) NOT NULL, 
	"Tran_State" VARCHAR(2) NOT NULL, 
	"Tran_Zip4" VARCHAR(10) NOT NULL, 
	"Tran_Emp" VARCHAR(50), 
	"Tran_Occ" VARCHAR(51), 
	"Tran_Self" BOOLEAN NOT NULL, 
	"Tran_Type" VARCHAR(4), 
	"Tran_Date" DATE NOT NULL, 
	"Tran_Date1" VARCHAR(32), 
	"Tran_Amt1" FLOAT NOT NULL, 
	"Tran_Amt2" FLOAT, 
	"Tran_Dscr" VARCHAR(28), 
	"Cmte_ID" VARCHAR(9), 
	"Tres_NamL" VARCHAR(32), 
	"Tres_NamF" VARCHAR(32), 
	"Tres_NamT" VARCHAR(32), 
	"Tres_NamS" VARCHAR(32), 
	"Tres_Adr1" VARCHAR(32), 
	"Tres_Adr2" VARCHAR(32), 
	"Tres_City" VARCHAR(32), 
	"Tres_State" VARCHAR(32), 
	"Tres_Zip" VARCHAR(32), 
	"Intr_NamL" VARCHAR(45), 
	"Intr_NamF" VARCHAR(32), 
	"Intr_NamT" VARCHAR(32), 
	"Intr_NamS" VARCHAR(32), 
	"Intr_Adr1" VARCHAR(32), 
	"Intr_Adr2" VARCHAR(32), 
	"Intr_City" VARCHAR(10), 
	"Intr_State" VARCHAR(4), 
	"Intr_Zip4" VARCHAR(10), 
	"Intr_Emp" VARCHAR(32), 
	"Intr_Occ" VARCHAR(32), 
	"Intr_Self" BOOLEAN NOT NULL, 
	"Cand_NamL" VARCHAR(32), 
	"Cand_NamF" VARCHAR(32), 
	"Cand_NamT" VARCHAR(32), 
	"Cand_NamS" VARCHAR(32), 
	"tblDetlTran_Office_Cd" VARCHAR(4), 
	"tblDetlTran_Offic_Dscr" VARCHAR(5), 
	"Juris_Cd" VARCHAR(4), 
	"Juris_Dscr" VARCHAR(11), 
	"Dist_No" VARCHAR(4), 
	"Off_S_H_Cd" VARCHAR(32), 
	"Bal_Name" VARCHAR(32), 
	"Bal_Num" VARCHAR(32), 
	"Bal_Juris" VARCHAR(32), 
	"Sup_Opp_Cd" VARCHAR(32), 
	"Memo_Code" VARCHAR(32), 
	"Memo_RefNo" VARCHAR(11), 
	"BakRef_TID" VARCHAR(32), 
	"XRef_SchNm" VARCHAR(32), 
	"XRef_Match" VARCHAR(32), 
	"Loan_Rate" FLOAT, 
	"Int_CmteId" VARCHAR(16)
);
