name: "New Check Google Drive Access"
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner}}
      REPO_BRANCH: ${{ github.ref_name }}
      SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
      GDRIVE_FOLDER: ${{ vars.GDRIVE_FOLDER }}
    steps:
    - uses: actions/checkout@v3
    - name: Build dev container
      uses: ./.devcontainer
    - name: Test pull from gdrive
      uses: ./.devcontainer
      with:
        entrypoint: bash
        args: ./.devcontainer/post-action-command.sh
    - name: Archive pulled files
      uses: actions/upload-artifact@v3
      with:
        name: redacted-netfile-files
        path: .local/downloads

