name: "Check Google Drive Access"
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner}}
      REPO_BRANCH: ${{ github.ref_name }}
      SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
      GDRIVE_FOLDER: ${{ vars.GDRIVE_FOLDER }}
    steps:
    - uses: actions/checkout@v3
    - run: "pip install -r gdrive_requirements.txt"
    - run: "python test_pull_from_gdrive.py"
    - name: Archive pulled files
      uses: actions/upload-artifact@v2
      with:
        name: redacted-netfile-files
        path: .local/downloads

